"""Parse control totals from the exact reports generated by 1C:Medicine.

Patient-level rows are deliberately discarded. Only report totals and safe
business dimensions (branch, specialty, doctor) leave this parser.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal, InvalidOperation
from io import BytesIO
from pathlib import Path
import re
import unicodedata

from openpyxl import load_workbook
import xlrd

from app.core.errors import AppError


@dataclass(frozen=True)
class ParsedMetric:
    metric_code: str
    value: Decimal
    dimension_type: str = "clinic"
    dimension_key: str = "clinic"
    dimension_label: str = "Вся клиника"
    branch_code: str | None = None
    unit: str = "KZT"
    details: dict = field(default_factory=dict)


@dataclass(frozen=True)
class ParsedOfficialReport:
    report_type: str
    metrics: list[ParsedMetric]
    summary: dict


@dataclass(frozen=True)
class SheetData:
    rows: list[list[object]]
    outline_levels: list[int]


REPORT_LABELS = {
    "cash_receipts": "Фактически поступившие деньги",
    "service_revenue": "Выручка по оказанным услугам",
    "payroll": "Начисление зарплаты",
    "doctor_revenue": "Выручка по врачам",
    "purchases": "Поступления и закупки",
    "patients": "Пациенты, посетившие клинику",
    "appointments": "Статистика предварительной записи",
}


def normalize_label(value: object) -> str:
    text = unicodedata.normalize("NFKC", str(value or "")).strip().casefold()
    return re.sub(r"\s+", " ", text)


def branch_code(value: object) -> str | None:
    text = normalize_label(value)
    if "батыс" in text:
        return "batysmura"
    if "сейф" in text:
        return "seifullina"
    return None


def _number(value: object) -> Decimal:
    if value in (None, ""):
        return Decimal("0")
    try:
        return Decimal(str(value).replace(" ", "").replace(",", "."))
    except (InvalidOperation, ValueError) as exc:
        raise AppError("INVALID_1C_REPORT", f"Некорректное числовое значение: {value}", 422) from exc


def _key(value: object) -> str:
    normalized = normalize_label(value)
    return re.sub(r"[^a-zа-яё0-9]+", "-", normalized).strip("-")[:300] or "unknown"


def _metric(
    code: str,
    value: object,
    *,
    dimension_type: str = "clinic",
    label: str = "Вся клиника",
    branch: str | None = None,
    unit: str = "KZT",
    details: dict | None = None,
) -> ParsedMetric:
    return ParsedMetric(
        metric_code=code,
        value=_number(value),
        dimension_type=dimension_type,
        dimension_key=branch or _key(label),
        dimension_label=str(label).strip(),
        branch_code=branch,
        unit=unit,
        details=details or {},
    )


def read_sheet(content: bytes, filename: str) -> SheetData:
    suffix = Path(filename).suffix.lower()
    try:
        if suffix == ".xls":
            book = xlrd.open_workbook(file_contents=content, formatting_info=True)
            sheet = book.sheet_by_index(0)
            rows = [[sheet.cell_value(row, col) for col in range(sheet.ncols)] for row in range(sheet.nrows)]
            levels = [sheet.rowinfo_map.get(row).outline_level if row in sheet.rowinfo_map else 0 for row in range(sheet.nrows)]
            return SheetData(rows=rows, outline_levels=levels)
        if suffix == ".xlsx":
            workbook = load_workbook(BytesIO(content), read_only=True, data_only=True)
            sheet = workbook.active
            rows = [list(row) for row in sheet.iter_rows(values_only=True)]
            levels = [0 for _ in rows]
            return SheetData(rows=rows, outline_levels=levels)
    except Exception as exc:
        raise AppError("INVALID_1C_REPORT", "Не удалось прочитать файл отчёта 1С", 422) from exc
    raise AppError("UNSUPPORTED_1C_REPORT", "Поддерживаются только .xls и .xlsx", 422)


def parse_official_report(content: bytes, filename: str) -> ParsedOfficialReport:
    sheet = read_sheet(content, filename)
    signature = " | ".join(
        normalize_label(cell) for row in sheet.rows[:8] for cell in row if cell not in (None, "")
    )
    if "банковский счет/касса" in signature and "выручка" in signature:
        return _parse_cash_receipts(sheet)
    if "номенклатура.специализация" in signature:
        return _parse_service_revenue(sheet)
    if "долг выплат" in signature and "начислено" in signature:
        return _parse_payroll(sheet)
    if "врач" in signature and "оплата от пациента" in signature:
        return _parse_doctor_revenue(sheet)
    if "имя объекта: поступление" in signature:
        return _parse_purchases(sheet)
    if "количество пациентов" in signature and "количество посещений" in signature:
        return _parse_patients(sheet)
    if "оформлено записей" in signature and "оформленно приемов" in signature:
        return _parse_appointments(sheet)
    raise AppError(
        "UNKNOWN_1C_REPORT",
        "Тип отчёта не распознан. Используйте один из семи согласованных отчётов 1С.",
        422,
    )


def _total_row(sheet: SheetData) -> list[object]:
    for row in reversed(sheet.rows):
        if row and normalize_label(row[0]) == "итого":
            return row
    raise AppError("INVALID_1C_REPORT", "В отчёте отсутствует строка «Итого»", 422)


def _parse_cash_receipts(sheet: SheetData) -> ParsedOfficialReport:
    total = _total_row(sheet)
    metrics = [_metric("revenue_payment", total[2]), _metric("cash_inflow", total[2])]
    return ParsedOfficialReport("cash_receipts", metrics, {"revenue_payment": str(metrics[0].value)})


def _parse_service_revenue(sheet: SheetData) -> ParsedOfficialReport:
    total = _total_row(sheet)
    metrics = [
        _metric("services_count", total[1], unit="count"),
        _metric("revenue_accrual", total[2]),
        _metric("revenue_before_discount", total[3]),
    ]
    current_branch: str | None = None
    for index, row in enumerate(sheet.rows[2:-1], start=2):
        if not row or not str(row[0] or "").strip():
            continue
        code = branch_code(row[0])
        if code:
            current_branch = code
            metrics.extend([
                _metric("services_count", row[1], dimension_type="branch", label=row[0], branch=code, unit="count"),
                _metric("revenue_accrual", row[2], dimension_type="branch", label=row[0], branch=code),
                _metric("revenue_before_discount", row[3], dimension_type="branch", label=row[0], branch=code),
            ])
        elif sheet.outline_levels[index] == 1 and current_branch:
            metrics.extend([
                _metric("services_count", row[1], dimension_type="specialty", label=row[0], branch=current_branch, unit="count"),
                _metric("revenue_accrual", row[2], dimension_type="specialty", label=row[0], branch=current_branch),
            ])
    return ParsedOfficialReport("service_revenue", metrics, {"revenue_accrual": str(_number(total[2]))})


def _parse_payroll(sheet: SheetData) -> ParsedOfficialReport:
    total = _total_row(sheet)
    metrics = [
        _metric("payroll_accrual", total[2]),
        _metric("payroll_paid", total[3]),
        _metric("payroll_due", total[4]),
    ]
    current_branch: str | None = None
    for index, row in enumerate(sheet.rows[3:-1], start=3):
        if not row or not str(row[0] or "").strip():
            continue
        code = branch_code(row[0])
        if code:
            current_branch = code
            metrics.extend([
                _metric("payroll_accrual", row[2], dimension_type="branch", label=row[0], branch=code),
                _metric("payroll_paid", row[3], dimension_type="branch", label=row[0], branch=code),
            ])
        elif sheet.outline_levels[index] == 1 and current_branch:
            metrics.append(_metric("payroll_accrual", row[2], dimension_type="employee", label=row[0], branch=current_branch))
    return ParsedOfficialReport("payroll", metrics, {"payroll_accrual": str(_number(total[2])), "payroll_paid": str(_number(total[3]))})


def _parse_doctor_revenue(sheet: SheetData) -> ParsedOfficialReport:
    total = _total_row(sheet)
    metrics = [_metric("doctor_revenue_payment", total[5])]
    current_branch: str | None = None
    for index, row in enumerate(sheet.rows[3:-1], start=3):
        if not row or not str(row[0] or "").strip():
            continue
        code = branch_code(row[0])
        if code:
            current_branch = code
            metrics.append(_metric("doctor_revenue_payment", row[5], dimension_type="branch", label=row[0], branch=code))
        elif sheet.outline_levels[index] == 1 and current_branch:
            metrics.append(_metric("doctor_revenue_payment", row[5], dimension_type="doctor", label=row[0], branch=current_branch))
    return ParsedOfficialReport("doctor_revenue", metrics, {"doctor_revenue_payment": str(_number(total[5]))})


def _parse_purchases(sheet: SheetData) -> ParsedOfficialReport:
    total = _total_row(sheet)
    metrics = [_metric("purchases_accrual_all_entities", total[20]), _metric("purchases_paid_all_entities", total[21])]
    # The export repeats a document total for each line. Count each document once.
    by_branch: dict[str, list[Decimal]] = {}
    seen_documents: set[str] = set()
    for row in sheet.rows[8:-1]:
        document = normalize_label(row[0] if row else "")
        if not document or document in seen_documents:
            continue
        seen_documents.add(document)
        code = branch_code(row[18] if len(row) > 18 else "")
        if code:
            totals = by_branch.setdefault(code, [Decimal("0"), Decimal("0")])
            totals[0] += _number(row[20])
            totals[1] += _number(row[21])
    san_accrual = sum((values[0] for values in by_branch.values()), Decimal("0"))
    san_paid = sum((values[1] for values in by_branch.values()), Decimal("0"))
    metrics.extend([_metric("purchases_accrual", san_accrual), _metric("purchases_paid", san_paid)])
    for code, values in by_branch.items():
        metrics.extend([
            _metric("purchases_accrual", values[0], dimension_type="branch", label=code, branch=code),
            _metric("purchases_paid", values[1], dimension_type="branch", label=code, branch=code),
        ])
    return ParsedOfficialReport("purchases", metrics, {"purchases_accrual": str(san_accrual), "purchases_paid": str(san_paid), "warning": "Закупки не равны признанным расходам P&L"})


def _parse_patients(sheet: SheetData) -> ParsedOfficialReport:
    total = _total_row(sheet)
    metrics = [
        _metric("patients_primary", total[2], unit="count"),
        _metric("patient_report_revenue", total[4]),
        _metric("patient_report_paid", total[5]),
    ]
    for row in sheet.rows[2:-1]:
        code = branch_code(row[0] if row else "")
        if not code:
            continue
        metrics.extend([
            _metric("patients_total", row[1], dimension_type="branch", label=row[0], branch=code, unit="count"),
            _metric("patients_primary", row[2], dimension_type="branch", label=row[0], branch=code, unit="count"),
            _metric("patient_visits", row[3], dimension_type="branch", label=row[0], branch=code, unit="count"),
        ])
    return ParsedOfficialReport("patients", metrics, {"patients_primary": str(_number(total[2])), "note": "Общий уникальный итог пациентов отсутствует в исходном отчёте"})


def _parse_appointments(sheet: SheetData) -> ParsedOfficialReport:
    total = _total_row(sheet)
    cancelled = 0
    no_show = 0
    for index, row in enumerate(sheet.rows[3:-1], start=3):
        if sheet.outline_levels[index] != 2 or len(row) < 4:
            continue
        status = normalize_label(row[2])
        reason = normalize_label(row[3])
        if "отмен" in status:
            cancelled += 1
        if "неяв" in status or "не приш" in status or "неяв" in reason or "не приш" in reason:
            no_show += 1
    metrics = [
        _metric("appointments_total", total[4], unit="count"),
        _metric("appointments_primary", total[5], unit="count"),
        _metric("appointments_completed", total[6], unit="count"),
        _metric("appointments_cancelled", cancelled, unit="count"),
        _metric("appointments_no_show", no_show, unit="count"),
        _metric("appointment_report_revenue", total[7]),
        _metric("appointment_report_paid", total[8]),
    ]
    for row in sheet.rows[3:-1]:
        code = branch_code(row[0] if row else "")
        if not code:
            continue
        metrics.extend([
            _metric("appointments_total", row[4], dimension_type="branch", label=row[0], branch=code, unit="count"),
            _metric("appointments_primary", row[5], dimension_type="branch", label=row[0], branch=code, unit="count"),
            _metric("appointments_completed", row[6], dimension_type="branch", label=row[0], branch=code, unit="count"),
        ])
    return ParsedOfficialReport("appointments", metrics, {"appointments_total": str(_number(total[4])), "appointments_completed": str(_number(total[6]))})
