const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000/api/v1";
export class ApiError extends Error { constructor(public status: number, message: string) { super(message); } }
type Session = { access_token: string; refresh_token: string };
let refreshInFlight: Promise<boolean> | null = null;
function session(): Session | null { if (typeof window === "undefined") return null; const raw = sessionStorage.getItem("revora_session"); try { return raw ? JSON.parse(raw) : null; } catch { return null; } }
async function refresh(): Promise<boolean> { const current = session(); if (!current?.refresh_token) return false; const response = await fetch(`${API_URL}/auth/refresh`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ refresh_token: current.refresh_token }) }); if (!response.ok) return false; const data = await response.json(); sessionStorage.setItem("revora_session", JSON.stringify(data)); sessionStorage.setItem("revora_user", JSON.stringify(data.user)); return true; }
export async function api<T>(path: string, init: RequestInit = {}, retry = true): Promise<T> { const current = session(); const headers = new Headers(init.headers); if (!(init.body instanceof FormData)) headers.set("Content-Type", "application/json"); if (current?.access_token) headers.set("Authorization", `Bearer ${current.access_token}`); const response = await fetch(`${API_URL}${path}`, { ...init, headers, cache: "no-store" }); if (response.status === 401 && retry && current?.refresh_token) { refreshInFlight ||= refresh().finally(() => { refreshInFlight = null; }); if (await refreshInFlight) return api<T>(path, init, false); } if (!response.ok) { let message = "Не удалось выполнить запрос"; try { const body = await response.json(); message = body.detail || body.error?.message || message; } catch {} throw new ApiError(response.status, message); } if (response.status === 204) return undefined as T; return response.json(); }
export async function apiBinary(path: string, init: RequestInit = {}): Promise<Response> { const current = session(); const headers = new Headers(init.headers); if (current?.access_token) headers.set("Authorization", `Bearer ${current.access_token}`); const response = await fetch(`${API_URL}${path}`, {...init, headers}); if (!response.ok) throw new ApiError(response.status, "Не удалось получить файл"); return response; }
export { API_URL };
